### ISSUE TITLE
Add Example for Ingress Configuration

### ISSUE THREAD

**Issue by anthu** [popecruzdt/easytravel-kubernetes#2]
In some environments HostPort is not a suitable approach.

An example could be added with ClusterIP Services and an example Ingress configuration eg. for commonly used Nginx Controller:

Eg.
```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: easytravel-frontend
  namespace: easytravel
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  tls:
    - hosts:
      - classic.easytravel.example.com
  rules:
    - host: classic.easytravel.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: easytravel-frontend-service
            servicePort: 8080
---
```
